// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "jquery"
import "jquery_ujs"
import "./jquery_ui"
import "@hotwired/turbo-rails"
import "controllers"
import "main"
import "swiper"
import "sticky"
import "datepicker"
